name = "sp-calculator"
compatibility_date = "2024-10-28"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[ d1_databases ]]
binding = "DATABASE"
database_name = "social-protection-calculator-db"
database_id = "b8537e66-55e0-4a56-a831-479a30eda038"
preview_database_id = "DATABASE" 
